# version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  python_app:
    build: .
    container_name: python_app
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/

volumes:
  mongo_data:
